### ISSUE TITLE
Update for new Atom syntax highlighting UI update

### ISSUE THREAD

**Issue by platocrat** [victorhqc/language-prisma#3]
After the new Atom update today, the Prisma plugin is no longer functional.
Now, all `.prisma` files appear as text files, with no syntax highlighting whatsoever.

This plugin was awesome previously and saved me lots of time (when it was working)!!

**Comment by victorhqc** [comment]
I'll take a look! Thank you for reporting 😄

**Comment by platocrat** [comment]
@victorhqc , the issue actually appears to be a minor issue.

After uninstalling `language-prisma` and reinstalling, the plugin works again as it should.

However, initially, after updating to the latest Atom version, all `.prisma`  files did appear as regular text files with no syntax highlighting.

**Comment by victorhqc** [comment]
Yes, its due to lack of rebuilding command by my side. I'm about to release a new minor fix 😄

**Comment by victorhqc** [comment]
Closing, as new release should fix it. Thanks for reporting @acecauis!
